[package]
name = "game_programming_dx12"
version = "0.1.0"
authors = ["dragonelite <thubie90@live.nl>"]

[dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"
kernel32-sys = "0.2.2"
gfxinfra = {path = "dxgi-rs"}

[workspace]